### ISSUE TITLE
Uniprot BLAST result contains entry name as id in REST API

### ISSUE THREAD

**Issue by jonblack** [cmbi/mrs#28]
Uniprot BLAST result contains the entry name in the id field instead of the Uniprot id. This is not guaranteed to be unique:

> Please note that it is highly recommended to use the accession number over the entry name, as the latter cannot be guaranteed to be stable:
> http://www.uniprot.org/help/difference_accession_entryname
> http://www.uniprot.org/help/entry_name :
> The entry name is a useful mnemonic means of identifying a sequence, but, unlike the accession number, it is not a stable identifier. It is sometimes necessary, for reasons of consistency, to change the entry name (for instance to ensure that related entries have similar names or when a UniProtKB/TrEMBL entry is integrated into UniProtKB/Swiss-Prot). We remind users that they should always use the primary accession number of an entry in any citation and link since it is the only unique stable identifier for an entry.

hope has been translating this entry name into a uniprot id by using the uniprot REST API. Specifically, that the API redirects entry names to the URL with the id. This is no longer the case, and although it may be a bug in the uniprot service, it has highlighted an issue with MRS. See issue https://github.com/cmbi/hope-flask/issues/65.

It would be useful to at least add the uniprot id to the result so it can be used instead. So keep the id field and add another field called `accession_code` or something similar. This ensures that nothing will break if id is being used.

**Comment by cbaakman** [comment]
In https://github.com/cmbi/hope/commit/83f80cea6e3ea21b2a58a4e589ccfcb8951c05ca, hope is changed so that it asks mrs for the uniprot accession code, that is linked to the id from the blast hit.
