### ISSUE TITLE
Blasting doesn't support non-standard amino acids

### ISSUE THREAD

**Issue by jonblack** [cmbi/mrs#45]
MRS returns the following error to HOPE when blasting swissprot with the sequence shown below:

>Query contains invalid characters

The web interface provides more information when you try to blast the same sequence:

>Query contains invalid characters: 'O'

```
MEFVALGGPDAGSPTPFPDEAGAFLGLGGGPRTEAGGLLASYPPSGRVSLVPWADTOTLGTPQWVPPATQMEPPHYLELLQPPRGSPPHPSSGPLLPLSSGPPPCEARECVNCGATATPLWRRDGTGHYLCNACGLYHRLNGQNRPLIRPKKRLLVSKRAGTVCSNCQTSTTTLWRRSPMGDPVCNACGLYYKLHQVNRPLTMRKDGIQTRNRKVSSKGKKRRPPGGONPSATAGGGAPMGGGGDPSMPPPPPPPAAAPPQSDALYALGPVVLSGHFLPFGNSGGFFGGGAGGYTAPPGLSPQI
```

`O` is the letter for `Pyrrolysine`, a non-standard amino acid. Should MRS support non-standard amino acids or is it correct to reject the query? Perhaps it should be an option? If not, the API error message should match the error message shown in the web interface.

**Comment by cbaakman** [comment]
It seems that the ncbi blast executable has no problems with it, so MRS should also support 'O'. We should be able to give 'O' some score values. Need to discuss this with Gert.
