### ISSUE TITLE
Error loading databank

### ISSUE THREAD

**Issue by jonblack** [cmbi/mrs#48]
The logs often contain messages about being unable to load databanks:

    [09/Nov/2016:19:15:57 UTC] Restarting services...Error loading databank embl
     >> Invalid page number
    Error loading databank oxford
     >> Invalid page number
    Error loading databank pfamb
     >> Invalid page number
    Error loading databank pmc
     >> Invalid page number

**Comment by cbaakman** [comment]
This seems to occur only with databanks that have been interrupted while building. So to get rid of these messages, we have to make each build run finish at least once, so that we have a completely indexed set with no zero page numbers in it.

**Comment by cbaakman** [comment]
https://github.com/cbaakman/mrs/commit/b05caa15fb81e122f9f83d1ba8dd78f0b2002bce disables two unbuildable databanks, pmc has now been built. We're still waiting for embl to complete building. Once that's done, I expect no more of the "Invalid page number" error.
