### ISSUE TITLE
Indexing EMBL takes up too many resources

### ISSUE THREAD

**Issue by jonblack** [cmbi/mrs#59]
When the EMBL indexing runs, rsyncing databanks from the server fails. We need to control how many resources MRS takes when performing the indexing. What options do we have?

**Comment by cbaakman** [comment]
what about ulimit?

**Comment by cbaakman** [comment]
I've discussed this with Gert. He said we should stop having embl in mrs.

**Comment by jonblack** [comment]
Sounds good to me.

**Comment by cbaakman** [comment]
Disabled embl in config
