### ISSUE TITLE
pdbfinder2 entries cannot be retrieved

### ISSUE THREAD

**Issue by touwwouter** [cmbi/mrs#60]
No matter how I try to get a pdbfinder2 entry, for every PDB identifier I end up at its pdbfinder entry rather than its pdbfinder2 entry.

* via clicking in the webinterface
* http://mrs.cmbi.ru.nl/entry?db=pdbfinder2&id=1crn

Or is there no distinction anymore?

**Comment by cbaakman** [comment]
I think it's the other way around actually. The pdbfinder2 entry is shown, even when pdbfinder is selected.

**Comment by touwwouter** [comment]
I agree

**Comment by cbaakman** [comment]
I see here https://github.com/cbaakman/mrs/blob/master/config/mrs-config.xml.dist#L110 that pdbfinder2 is just an alias for pdbfinder, and that the input file is actually the pdbfinder2 file. We might need to change this.

**Comment by touwwouter** [comment]
I think it is fine to always give pdbfinder2 files.
